feat: support for split data files
team-apm/apm pull request #540
Opened 2022-05-06 14:11 UTC by mitosagi

## Description

Supports split `packages` data files and `scripts` data files. Also, relative paths for data files, except for `list.json`, will be available.

If apm-schema in your `node_modules` is not up to date, please run `yarn upgrade apm-schema`.

### Progress
- [x] Implementation
- [ ] Preparation of test data

## Related Issue

- https://github.com/team-apm/apm-data/issues/122

This PR depends on the following PR(s)
- https://github.com/team-apm/apm/pull/532

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-08 13:03 UTC, hal-shu-sato requested changes
I know this is a draft, but I review it. Sorry.

2022-05-08 13:03 UTC, hal-shu-sato commented on src/lib/modList.ts
> +    return new URL(relative, base).href;
This code may download data from external hosts or other directories, which is a security concern.

2022-05-08 13:06 UTC, hal-shu-sato commented on src/lib/modList.ts
> +    return new URL(relative, base).href;
Refer to the last example on this page: https://developer.mozilla.org/ja/docs/Web/API/URL/URL

2022-05-09 18:00 UTC, yumetodo commented on src/lib/modList.ts
> +    return new URL(relative, base).href;
b6c2ea1 seems goot to me.

2022-05-12 13:27 UTC, mitosagi commented
Rebased. No change in code.

2022-05-15 03:25 UTC, hal-shu-sato approved these changes
It works fine.

2022-05-15 03:25 UTC, merged