feat: add listing the nicommons IDs of the installed packages
team-apm/apm pull request #569
Opened 2022-05-21 14:05 UTC by hal-shu-sato

## Description

- Add listing the nicommons IDs of the installed packages.

## Related Issue

close #271

## Motivation and Context

## How Has This Been Tested?

- I will add nicommons ID into the data.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-22 11:50 UTC, mitosagi requested changes
Great UI, very easy to read. The code is also basically fine.

There are a few things I would check.
`modList.ts`  has an existing bug that can be fixed as follows.
```diff
async function getInfo() {
  const modFile = await ipcRenderer.invoke('exists-temp-file', 'list.json');
  if (modFile.exists) {
    try {
      return await parseJson.getMod(modFile.path);
    } catch {
      return null;
    }
  } else {
-    return null;
+   await downloadData();
+   const downloadedModFile = await ipcRenderer.invoke('exists-temp-file', 'list.json');
+   try {
+     return await parseJson.getMod(downloadedModFile.path);
+   } catch {
+     return null;
+   }
  }
}
```
If I make this modification to PR and then launch apm from the `yarn package` with a clean install, it does not seem to work. However, the one with this modification on the `main` branch does work with a clean install. I do not know why.

2022-05-22 11:50 UTC, mitosagi commented on src/renderer/main/preload.ts
> +window.addEventListener('load', async () => {
Might not be necessary.

2022-05-22 14:57 UTC, mitosagi commented on forge.config.js
> +          "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data: https://twemoji.maxcdn.com/ *.nicovideo.jp *.nicoseiga.jp nicovideo.cdn.nimg.jp",
```suggestion
          "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data: https://twemoji.maxcdn.com/ https://*.nicovideo.jp https://*.nicoseiga.jp https://nicovideo.cdn.nimg.jp",
```

2022-05-22 14:58 UTC, mitosagi commented on src/renderer/main/index.html
> +			content="default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data: https://twemoji.maxcdn.com/ *.nicovideo.jp *.nicoseiga.jp nicovideo.cdn.nimg.jp"
```suggestion
			content="default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data: https://twemoji.maxcdn.com/ https://*.nicovideo.jp https://*.nicoseiga.jp https://nicovideo.cdn.nimg.jp"
```

2022-05-22 15:01 UTC, mitosagi commented on forge.config.js
> +          "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data: https://twemoji.maxcdn.com/ *.nicovideo.jp *.nicoseiga.jp nicovideo.cdn.nimg.jp",
The packaged version of apm can load images with the following changes.

2022-05-22 15:21 UTC, mitosagi commented
> Great UI, very easy to read. The code is also basically fine.
> 
> There are a few things I would check. `modList.ts` has an existing bug that can be fixed as follows.
> 
> ```diff
> async function getInfo() {
>   const modFile = await ipcRenderer.invoke('exists-temp-file', 'list.json');
>   if (modFile.exists) {
>     try {
>       return await parseJson.getMod(modFile.path);
>     } catch {
>       return null;
>     }
>   } else {
> -    return null;
> +   await downloadData();
> +   const downloadedModFile = await ipcRenderer.invoke('exists-temp-file', 'list.json');
> +   try {
> +     return await parseJson.getMod(downloadedModFile.path);
> +   } catch {
> +     return null;
> +   }
>   }
> }
> ```
> 
> If I make this modification to PR and then launch apm from the `yarn package` with a clean install, it does not seem to work. However, the one with this modification on the `main` branch does work with a clean install. I do not know why.

The cause seems to be ClipboardJS.

2022-05-26 04:41 UTC, hal-shu-sato commented
I fixed them.
I want to merge this PR after merging #570.

2022-05-28 07:12 UTC, mitosagi submitted a review, later dismissed
It works fine.

The ClipboardJS loading error seems to be something that existed before this PR.

2022-05-28 16:28 UTC, hal-shu-sato commented
I rebased.

2022-05-29 03:40 UTC, mitosagi approved these changes
OK

2022-05-29 05:42 UTC, merged