refactor: migrate to TypeScript
team-apm/apm pull request #654
Opened 2022-06-19 12:11 UTC by hal-shu-sato

## Description

- Migrate to TypeScript.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-09 03:24 UTC, mitosagi requested changes
I would like to confirm a several things.

Also, could you please remove all lines starting with ` /** @typedef` or `/** @type`, that are no longer needed due to the transition to TypeScript?

2022-07-09 03:24 UTC, mitosagi commented on src/lib/apmJson.ts
> +function getApmJson(instPath: string) {
```suggestion
function getApmJson(instPath: string): ApmJsonObject {
```
Corresponding to the below.

2022-07-09 03:24 UTC, mitosagi commented on src/lib/apmJson.ts
> +    return { dataVersion: '3', core: {}, packages: {} } as ApmJsonObject;
```suggestion
    return { dataVersion: '3', core: {}, packages: {} };
```

It may be better not to put `as` on objects that are entered manually.

2022-07-09 03:24 UTC, mitosagi commented on src/lib/buttonTransition.ts
>    if (type != null) {
```suggestion
  type?: string
) {
  if (type) {
```

2022-07-09 03:24 UTC, mitosagi commented on src/lib/updatableList.ts
> +) {
```suggestion
): List {
```

This is perhaps my preference, though.

2022-07-09 03:24 UTC, mitosagi commented on src/renderer/main/package.ts
>    const packagesWithNicommonsId = [
```suggestion
  const packagesWithNicommonsId: PackageItemWithNicommonsId[] = [
```

2022-07-09 03:24 UTC, mitosagi commented on src/renderer/main/package.ts
> +    } as PackageItemWithNicommonsId,
```suggestion
    },
```

It may be better not to put `as` on objects that are entered manually.

2022-07-09 03:24 UTC, mitosagi commented on src/renderer/main/package.ts
> +    } as PackageItemWithNicommonsId,
```suggestion
    },
```

same

2022-07-09 03:24 UTC, mitosagi commented on src/renderer/main/packageUtil.ts
> +  | '.scn';
```suggestion
type aviutlExtention = keyof typeof typeForExtention;
```

2022-07-10 08:26 UTC, hal-shu-sato commented
I fixed them.

2022-07-11 11:32 UTC, mitosagi approved these changes
Goodbye JavaScript, Hello TypeScript.

2022-07-11 11:37 UTC, merged