fix: Garbled filename when unzipped
team-apm/apm pull request #682
Opened 2022-07-01 16:36 UTC by FOBshippingpoint

## Description
- Change code page to 932(Shift_JIS).
- Refactor: simplify pathTo7zip settings.

## Related Issue
- fix #680 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-02 16:21 UTC, mitosagi requested changes
I just want to confirm one thing.

2022-07-02 16:21 UTC, mitosagi commented on src/lib/unzip.js
> +if (isDevEnv) {
Probably inverted.

2022-07-02 19:34 UTC, FOBshippingpoint commented on src/lib/unzip.js
> +if (isDevEnv) {
Yes, I will fix this.

2022-07-03 01:00 UTC, mitosagi approved these changes
Looks good to me.

2022-07-04 04:24 UTC, hal-shu-sato requested changes
I have one point to review.

2022-07-04 04:24 UTC, hal-shu-sato commented on src/lib/unzip.js
> +  pathTo7zip.replace('app.asar', 'app.asar.unpacked');
`String.replace()` does not change the object.
It just returns a new string.
```suggestion
  pathTo7zip = pathTo7zip.replace('app.asar', 'app.asar.unpacked');
```

2022-07-04 04:24 UTC, hal-shu-sato commented on src/lib/unzip.js
> +const pathTo7zip = process.platform === 'win32' ? win7zip['7z'] : path7za;
```suggestion
let pathTo7zip = process.platform === 'win32' ? win7zip['7z'] : path7za;
```

2022-07-04 05:31 UTC, FOBshippingpoint commented on src/lib/unzip.js
> +  pathTo7zip.replace('app.asar', 'app.asar.unpacked');
Sorry for this stupid mistake. I fixed the problem. I will pay more attention next time.

2022-07-04 06:07 UTC, hal-shu-sato commented on src/lib/unzip.js
> +  pathTo7zip.replace('app.asar', 'app.asar.unpacked');
Please do not say such a thing.
We, everyone, could make a mistake.
It is OK.

2022-07-04 06:08 UTC, hal-shu-sato approved these changes
Thank you for fixing it and contributing to apm!

2022-07-04 06:23 UTC, merged